# Generated by Django 4.1.5 on 2023-01-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_orders_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
